// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKb3varOU0VksKhcHElUN1g864xTJNNg8',
    appId: '1:794247543473:web:fcbaf4c6225d481f498090',
    messagingSenderId: '794247543473',
    projectId: 'aastha-tiktok-clone',
    authDomain: 'aastha-tiktok-clone.firebaseapp.com',
    storageBucket: 'aastha-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQ2ALtoj26zzQZhhv3E9yJSMv9JonwwA',
    appId: '1:794247543473:android:906da4c29ab3e45a498090',
    messagingSenderId: '794247543473',
    projectId: 'aastha-tiktok-clone',
    storageBucket: 'aastha-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9n4MmmJK6dNGw1Sy3fzfcBcERLyaMeFg',
    appId: '1:794247543473:ios:be837ee7b2ed8600498090',
    messagingSenderId: '794247543473',
    projectId: 'aastha-tiktok-clone',
    storageBucket: 'aastha-tiktok-clone.appspot.com',
    iosClientId: '794247543473-mip90dqvskheti7fr99ukia2rmbhppff.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9n4MmmJK6dNGw1Sy3fzfcBcERLyaMeFg',
    appId: '1:794247543473:ios:a5faf29ccca8f8f3498090',
    messagingSenderId: '794247543473',
    projectId: 'aastha-tiktok-clone',
    storageBucket: 'aastha-tiktok-clone.appspot.com',
    iosClientId: '794247543473-mh1s7d4097sag69dput72lftimel0vou.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
